config/routes.rb
Diacode13::Application.routes.draw do
  root :to => 'pages#index'

  get 'services' => 'pages#services'
  get "work" => "pages#work"

  resources :inquiries, path: 'contact', :only => [:new, :create], 
            path_names: { :new => ''}
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :message, :interested_in
  validates :name, :email, :message, :interested_in, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} } #, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    
    if @inquiry.valid?
      MessageMailer.contact_notification(@inquiry).deliver
      redirect_to(new_inquiry_url, :notice => "Message was successfully sent.")
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def services
  end

  def work
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inquiries/new.html.haml
- content_for :title, 'Contact - Diacode'

#contact
  %h2.text-center LET'S TALK
  = form_for @inquiry do |f|
    .row
      .span8.offset2
        - if @inquiry.errors.any?
          .alert.alert-error
            %p There are empty fields.

        - if flash[:notice]
          .alert.alert-success
            %p= flash[:notice]

    .row
      .span3.offset2
        = f.label :name
        = f.text_field :name, class: 'span3'
        = f.label :email
        = f.email_field :email, class: 'span3'
        = f.label :phone
        = f.text_field :phone, class: 'span3'
        = f.label :interested_in
        = f.select :interested_in, options_for_select(['Development', 'Training', 'Consultancy', 'Other']), class: 'span3'

      .span5 
        = f.label :message
        = f.text_area :message, class: 'span5', rows: '8'

        = submit_tag "Send", class: 'button'


  %hr
    %p.text-center.muted
      Prefer a simple email? 
      %br
      %i.icon-envelope
      %em hello@diacode.com

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-sc ale=1"}
    %title= content_for?(:title) ? yield(:title) : "Diacode - Handcrafted web development"
    %meta{:content => content_for?(:description) ? yield(:description) : "Diacode is a Ruby on Rails development boutique. We craft apps for web and mobile with love and passion.", :name => "description"}
    %meta{:content => "Diacode", :name => "author"}

    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Arvo", :media => "all"
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700", :media => "all"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'shared/analytics'

  %body{data: {spy: "scroll", target: "#subnav"}}
    = render 'shared/header'
    .container= yield
    = render "shared/footer"  
    

app/views/pages/index.html.haml
#home
  .row
    .span10.offset1
      %h1= image_tag "handcrafted.png", alt: 'Handcrafted Web Development'
      #hammer.text-center
        = image_tag "hammer.png"

      %p
        %strong Diacode is a full stack Ruby on Rails development shop. 
        We craft apps for web and mobile with love and passion.

      %p
        Since 2010, we have been helping organizations transform their ideas into beautiful, expertly engineered web applications.
        We love helping you turn your vision into reality, putting our heart into every line of code we craft, and every pixel we create.

      %p
        Our methodology is designed to be flexible to your needs, taking an agile approach to testing, continuous integration, and delivery. 
        We use our comprehensive knowledge of Ruby, Rails, and the related ecosystem to meet your goals and solve the technological challenges facing your business.

      %p
        %strong Great ideas, beautiful designs, and professional code - every time.
  %hr
  #services.row
    .span4.text-center
      .service
        %i.icon-cogs
        %h4=link_to "DEVELOPMENT", services_path(anchor: 'development')
        %p
          Crafting new products is our passion. We use the right tools that allow us
          to deliver high quality applications for mobile and the web.
    
    .span4.text-center
      .service
        %i.icon-bullhorn
        %h4=link_to "TRAINING", services_path(anchor: 'training')
        %p
          Sometimes hands-on learning is the key to taking your Ruby on Rails knowledge to the next level. 
          We enjoy teaching others and passing on our knowledge.

    .span4.text-center
      .service
        %i.icon-lightbulb
        %h4=link_to "CONSULTING", services_path(anchor: 'consulting')
        %p
          If you need help with your project, we can team up with you and put your project back on the right track.
  .row
    .span12.text-center
      #call-to-action= link_to "Kickstart your project now", new_inquiry_path, class: 'button'

app/views/pages/services.html.haml
- content_for :title, 'Services - Diacode'

- content_for :subnav do
  %h2#title.text-center
    WE LOVE WHAT WE DO
    %br
    %span SO WE DO IT RIGHT

  #subnav
    .wrapper{data: {spy: "affix", offset: {top: "236"}, affix: {top: '0'}}}
      .container
        %ul.inline.text-center.nav
          %li 
            %a{href: "#process"} PROCESS
          %li 
            %a{href: "#development"} DEVELOPMENT
          %li
            %a{href: "#training"} TRAINING
          %li
            %a{href: "#consulting"} CONSULTING


#services
  #process
    .row
      .span8.offset2
        %h3.text-center OUR PROCESS
        %p
          During the last years we have been improving our workflow in order to boost productivity and ensure complete success and satisfaction. This how we craft:

    .row
      .span2.offset2.text-center
        = image_tag "ico-research.png"
      .span6
        %h4 RESEARCH AND BRAINSTORMING
        %p
          We start working with you in order to define your product. In addition to analyze what the technical details are, we will help you
          to improve your product and business model.

    .row
      .span2.offset2.text-center
        = image_tag "ico-sketch.png"
      .span6
        %h4 WIREFRAMING AND STORYCARDING
        %p
          Once we got the idea of your product clear, we'll start wireframing and writing the users stories. Then we'll sort the stories
          in the order thar uncover more business value to your product.

    .row
      .span2.offset2.text-center
        = image_tag "ico-development.png"
      .span6
        %h4 DEVELOPMENT AND DELIVERY
        %p
          Following a Behavior Driven Development (BDD) approach we'll transform the users stories we wrote into acceptance tests that will
          guide our development process, ensuring that at any time the software created is bulletproof. In each iteration we'll delivery
          a fully function version of your product.

  %hr
  #development
    .row
      .span12
        %h3.text-center DEVELOPMENT
    #services.row
      .span5.text-center.offset1
        .service
          %i.icon-bolt
          %h4 KICKSTART
          %p
            %strong 3 weeks intensive process where we'll build your Minimum Viable Product (MVP)
            following the Lean Startup principles. 
          %p.muted
            $ 7000 (USD) / week
      .span5.text-center
        .service
          %i.icon-time
          %h4 HOURLY RATE
          %p
            You can also hire us with an hourly base rate per developer. We track our time precisely and only charge for real and valuable work.
          %p.muted
            $ 100 (USD) / hour
    %p.text-center
      = link_to "Hire us for crafting your product", new_inquiry_path, class: 'button'

  %hr
  #training
    .row
      .span12
        %h3.text-center TRAINING
    .row
      .span8.offset2
        %p 
          Formal education is broken. We didn't learn our craft in a formal way so we love to explore new ways to teach people and share our knowledge. Often we run free talks and workshops where we teach Ruby on Rails and other technologies to anyone interested. Here are some of our recent talks:
          %ul.talks
            %li=link_to "Front-End Frameworks: a quick overview", "http://www.slideshare.net/Diacode/frontend-frameworks-a-quick-overview", target: "_blank"
            %li=link_to "Education: The Next Big Thing", "http://www.slideshare.net/Diacode/educacin-the-next-big-thing", target: "_blank"
            %li=link_to "Introduction to HTML5 and CSS3 (Spanish)", "http://talks.diacode.com/html5/index.html", target: "_blank"
            %li=link_to "Introduction to Ruby on Rails (Spanish): part 1", "http://www.slideshare.net/Diacode/taller-de-introduccin-a-ruby-on-rails", target: "_blank"
            %li=link_to "Introduction to Ruby on Rails (Spanish): part 2", "http://www.slideshare.net/Diacode/talle-de-introduccin-a-ruby-on-rails-2-parte", target: "_blank"
        %p You can also hire us for training you in any of our expertise areas.
        %p.text-center
          = link_to "Hire us for training", new_inquiry_path, class: 'button'
  %hr
 
  #consulting
    .row
      .span12
        %h3.text-center CONSULTING
    .row
      .span8.offset2
        %p
          We can team up with you and your team in order to share our know how and give you insights on how to place your project back in the right track
          using Agile methodologies and Behavior Driven Developmet. In addition we'll assist you on getting more convertions and uncovering more
          business value.
        %p.text-center
          = link_to "Hire us for consulting", new_inquiry_path, class: 'button'
  %hr

app/views/pages/work.html.haml
- content_for :title, 'Work - Diacode'

#work
  .row
    .span10.offset1
      %h2.text-center THINGS WE ARE PROUD OF

      %p
        We've been in business for a long time so listing here all the projects we have worked on would be quite boring, so here are some of the projects we're most proud of. If you want to see your project here, we should 
        = link_to "get in touch.", new_inquiry_path

  %hr

  #projects
    .row.project
      .span6
        = image_tag "work/civvic.png", class: "snapshot"
      
      .span6
        %h3 Civvic

        .description
          %p
            Civvic enables energy project research, financial analysis, and decision making by providing an API. We help
            the team at Civvic building the very first version of their website and their corporate identity in just two days.
          %ul.muted
            %li Ruby on Rails
            %li HTML5 / CSS3 / CoffeeScript
            %li Twitter Bootstrap
            %li Photoshop
        / %ul
        /   %li Ruby On Rails
        .links
          = link_to "Visit", "http://civvic.com", class: "button", target: '_blank'
    
    .row.project
      .span6
        = image_tag "work/skunkhacks.png", class: "snapshot"
      
      .span6
        %h3 Skunkhacks

        .description
          %p
            During a hackathon in Hacker Dojo (Mountain View, CA) we built the website for the SkunkHacks team, a group of awesome hackers who are doing an amazing work in CleanWeb related stuff.
          %ul.muted
            %li Ruby on Rails
            %li HTML5 / CSS3 / CoffeeScript
            %li Twitter Bootstrap
            %li Photoshop / Illustrator
        / %ul
        /   %li Ruby On Rails
        .links
          = link_to "Visit", "http://skunkhacks.com", class: "button", target: '_blank'
    
    .row.project
      .span6
        = image_tag "work/gudog.png", class: "snapshot"
      
      .span6
        %h3 Gudog

        .description
          %p
            A p2p marketplace that helps dog owners find a caregiver (dog sitter, dog walker, etc.) for their dogs. 
          %ul.muted
            %li Ruby on Rails
            %li MySQL / Sphinx
            %li HTML5 / CSS3 / CoffeeScript
            %li RSpec / Cucumber / Capybara
            %li Paypal Adaptive Payments API
        / %ul
        /   %li Ruby On Rails
        .links
          = link_to "Visit", "http://gudog.com", class: "button", target: '_blank'
    
    %hr

    .row.project
      .span6
        = image_tag "work/adopta-gudog.png", class: "snapshot"
      
      .span6
        %h3 Adopta Gudog

        .description
          %p 
            Side project from Gudog that aims to promote dog adoption, helping dog shelters to spread the word about the dogs they have in adoption.

          %ul.muted
            %li Ruby on Rails
            %li MongoDB
            %li HTML5 / CSS3 / CoffeeScript
            %li RSpec / Capybara

        .links
          = link_to "Visit", "http://adopta.gudog.com", class: "button", target: '_blank'

    %hr
    .row.project
      .span6
        = image_tag "work/sprak.png", class: "snapshot"
    
      .span6
        %h3 Språk

        .description
          %p 
            Exprimental open source app built during the LAUNCH Hackathon 2013 in San Francisco. Winner of the second prize from Tokbox.

          %ul.muted
            %li Ruby on Rails
            %li WebRTC / P2P Video chat
            %li HTML5 / CSS3 / CoffeeScript

        .links
          = link_to "View code", "http://github.com/diacode/sprak", class: "button", target: '_blank'

    %hr

    .row.project
      .span6
        = image_tag "work/jurintia.png", class: "snapshot"
      
      .span6
        %h3 Jurintia

        .description
          %p 
            A web appications for helping solicitors (a special type of attorney) in their daily job. You can think about it as a full project manager for solicitors.

          %ul.muted
            %li Ruby on Rails
            %li MySQL / Sphinx
            %li HTML5 / CSS3 / CoffeeScript
            %li RSpec / Capybara
            %li OCR

        / %ul
        /   %li Ruby On Rails
        .links
          = link_to "Visit", "http://jurintia.com", class: "button", target: '_blank'

    %hr

    .row.project
      .span6
        = image_tag "work/thickzine.png", class: "snapshot"
      
      .span6
        %h3 Thickzine

        .description
          %p 
            Webzine in Spanish about design, longboard, music and trash culture.
          %ul.muted
            %li Ruby on Rails
            %li MySQL
            %li RSpec / Capybara
            %li HTML5 / CSS3 / CoffeeScript

        .links
          = link_to "Visit", "http://thickzine.com", class: "button", target: '_blank'

    %hr

    .row.project
      .span6
        = image_tag "work/versosperfectos.png", class: "snapshot"
      
      .span6
        %h3 Versos Perfectos

        .description
          %p
            Hip Hop database and webzine in spanish. It's and old project (launched on 2008) and is still the most recognized website in the spanish Hip Hop scene. It features a complex database with data from more than 3500 different artists, including discography, lyrics, bio and pictures.
          %ul.muted
            %li PHP
            %li Doctrine as ORM
            %li MySQL
            %li Homegrown framework
        .links
          = link_to "Visit", "http://versosperfectos.com", class: "button", target: '_blank'

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18217579-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_footer.html.haml
%footer#footer
  .container
    .row
      .span2
        %h4 FOLLOW US
        %ul.unstyled
          %li
            %i.icon-twitter
            = link_to "Twitter", "http://twitter.com/diacode", target: "_blank"
          %li
            %i.icon-facebook-sign
            = link_to "Facebook", "http://facebook.com/diacode", target: "_blank"

      .span5
        %h4 OUR BLOG IN SPANISH
        %p
          While we are fluent in English, we love sharing our knowledge and promoting technology to the Spanish speaking community. 
          = link_to "Check it out here.", "http://blog.diacode.com", target: "_blank"
      .span5
        %h4 HIRE US
        %p
          = link_to "Get in touch.", new_inquiry_path
          We cannot wait to build your next great idea.
    %p.end-line
      %small 
        Crafted with 
        ♥
        in San Francisco, CA. March 2013.
        %br
      %i.icon-github
      %small=link_to "Source code", "http://github.com/diacode/diacode13", target: '"_blank'

app/views/shared/_header.html.haml
%header#header
  .container
    .pull-left
      = link_to image_tag("logo-flat.png"), root_path
    .pull-right
      %ul.inline
        %li{class: ("active" if action_name == 'index')}
          = link_to "HOME", root_path
        %li{class: ("active" if action_name == 'work')}
          = link_to "WORK", work_path
        %li{class: ("active" if action_name == 'services')}
          = link_to "SERVICES", services_path
        %li{class: ("active" if controller_name == 'inquiries')}
          = link_to "CONTACT", new_inquiry_path
    .clearfix
= yield :subnav